[tool.poetry]
name = "potest"
version = "0.1.0"
description = ""
authors = ["Seth Stadick <sstadick@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.7"
nimporter = "^0.1.5"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
